kind = "web"
previewPath = "/"
title = "41M4"
version = "1.0.0"
id = "artifacts/41m4"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22875

[services.development]
run = "pnpm --filter @workspace/41m4 run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/41m4", "run", "build" ]
publicDir = "artifacts/41m4/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22875"
BASE_PATH = "/"
